"""Success-check executors.

A task YAML lists `success_checks`; ALL must pass for the trial to count as
a success (the binary primary outcome behind H1). Three families of check
exist, distinguished by what they read:

  * Snapshot-only — pure functions of the post-run FilesystemSnapshot:
    file_exists, directory_exists, file_is_empty, no_extra_files,
    no_files_matching.

  * Baseline-relative — compare the post-run snapshot with the pre-agent
    snapshot supplied by the runner: file_unchanged.

  * Sandbox-content — read file bytes from the host filesystem. They need
    the sandbox host root, supplied via `evaluate_checks(...,
    sandbox_host_root=...)`. If it is not provided they fail closed:
    python_parses, file_contains_substring_count, file_content_equals,
    json_content_equals, file_count_matching.

  * Agent-trace — read the per-command stdout / stderr the agent issued
    during the trial. They need the agent's CommandRecord list, supplied
    via `evaluate_checks(..., agent_commands=...)`. If it is not provided
    they fail closed: agent_any_command_stdout_equals,
    agent_all_command_stderrs_empty.

  * Environment-oracle — execute a fixed argv (never a shell string) in the
    selected environment after the agent returns: environment_command.

Adding a new check type = add one function + one `@check("name")` + (if
the check needs context) one entry in `_CONTEXT_CHECKS` or
`_AGENT_CHECKS`. The runner calls `evaluate_checks` and never needs to
know the catalogue.

Path convention: all paths are sandbox-relative POSIX, matching
`FilesystemSnapshot`. A leading "./" in the YAML is tolerated and stripped.

Ignored artefacts: `__pycache__/` directories and `.pyc` / `.pyo` / `.pyd`
files are excluded from `no_extra_files` / `no_files_matching` /
`file_count_matching` and are never the target of a content check. They
are import-side-effect artefacts of any Python verification step (e.g.
an agent that runs `python -c "import lib"` to sanity-check its work).
Counting them as "extras" would penalise the more diligent agent — a
denominator-bias failure mode the pre-registration explicitly avoids.
"""

from __future__ import annotations

import ast
import fnmatch
import json
import re
import sys
from datetime import datetime, timedelta
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import Any

from .types import CheckResult, FilesystemSnapshot

CheckFn = Callable[[FilesystemSnapshot, Mapping[str, object]], CheckResult]

_REGISTRY: dict[str, CheckFn] = {}

# Python import-cache artefacts. Generated by ANY `python -c "import ..."`
# verification an agent may run; would otherwise spuriously fail
# no_extra_files / no_files_matching / file_count_matching. Listed here,
# not per-task, so the rule is uniform and auditable.
_IGNORE_DIR_NAMES: frozenset[str] = frozenset({
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
})
_IGNORE_FILE_SUFFIXES: tuple[str, ...] = (".pyc", ".pyo", ".pyd")

# Check types that need to read file content from the host filesystem.
# evaluate_checks injects the sandbox host root into these specs.
_CONTEXT_CHECKS: frozenset[str] = frozenset({
    "python_parses",
    "file_contains_substring_count",
    "file_content_equals",
    "json_content_equals",
    "file_count_matching",
})

# Check types that need the agent's per-command transcript.
# evaluate_checks injects the agent_commands sequence into these specs.
_AGENT_CHECKS: frozenset[str] = frozenset({
    "agent_any_command_stdout_equals",
    "agent_all_command_stderrs_empty",
})
_ENVIRONMENT_CHECKS: frozenset[str] = frozenset({"environment_command"})
_BASELINE_CHECKS: frozenset[str] = frozenset({"file_unchanged"})
_ENVIRONMENT_CHECK_ENV: Mapping[str, str] = {
    "ALL_PROXY": "",
    "HTTPS_PROXY": "",
    "HTTP_PROXY": "",
    "NO_PROXY": "127.0.0.1,localhost,::1",
    "all_proxy": "",
    "https_proxy": "",
    "http_proxy": "",
    "no_proxy": "127.0.0.1,localhost,::1",
}
_PYTHON_COMPAT_DIR = Path(__file__).resolve().parent / "python_compat"


def _environment_check_env() -> Mapping[str, str]:
    """Return the isolated oracle environment, plus platform compatibility.

    GitHub's macOS 15+ runners can stall in ``socket.getfqdn()`` between a
    Python HTTP server's bind and listen calls.  The injected ``sitecustomize``
    is deliberately limited to Darwin ``service.py --once`` processes and
    loopback names, matching the runner-images maintainers' documented
    workaround without changing frozen task bytes.
    """
    env = dict(_ENVIRONMENT_CHECK_ENV)
    if sys.platform == "darwin":
        env["PYTHONPATH"] = str(_PYTHON_COMPAT_DIR)
    return env


def check(name: str) -> Callable[[CheckFn], CheckFn]:
    def register(fn: CheckFn) -> CheckFn:
        _REGISTRY[name] = fn
        return fn

    return register


def requires_agent_trace(specs: Sequence[Mapping[str, object]]) -> bool:
    """Whether any registered H1 check depends on recovered command traces."""
    return any(str(spec.get("type", "")) in _AGENT_CHECKS for spec in specs)


def registered_check_types() -> frozenset[str]:
    """Names of the executable H1 checks registered in this build.

    Qualification linting consumes this live registry rather than maintaining
    a second allowlist that could itself drift from collection behavior.
    """
    return frozenset(_REGISTRY)


@check("environment_command")
def _environment_command(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Run a frozen argv-based oracle inside the measured environment."""
    del snap
    executor = spec.get("_environment_exec")
    cwd = spec.get("_environment_cwd")
    if not callable(executor) or not isinstance(cwd, str) or not cwd:
        return CheckResult(
            "environment_command",
            False,
            "environment execution context unavailable",
        )
    allowed = {
        "type", "argv", "returncode", "stdout", "stderr_empty",
        "timeout_seconds", "_environment_exec", "_environment_cwd",
    }
    if set(spec) - allowed:
        return CheckResult(
            "environment_command", False, "environment_command has unknown fields"
        )
    argv = spec.get("argv")
    if not isinstance(argv, list) or not argv or any(
        not isinstance(item, str) or not item for item in argv
    ):
        return CheckResult(
            "environment_command", False, "argv must be a non-empty string list"
        )
    expected_rc = spec.get("returncode", 0)
    timeout = spec.get("timeout_seconds", 30)
    if (
        isinstance(expected_rc, bool)
        or not isinstance(expected_rc, int)
        or isinstance(timeout, bool)
        or not isinstance(timeout, (int, float))
        or not 0 < float(timeout) <= 30
    ):
        return CheckResult(
            "environment_command", False, "invalid returncode or timeout"
        )
    result = executor(
        argv,
        cwd=cwd,
        timeout=float(timeout),
        env=_environment_check_env(),
    )
    stdout = _normalise_lineendings(result.stdout or "")
    stderr = _normalise_lineendings(result.stderr or "")
    passed = not result.timed_out and result.returncode == expected_rc
    details = [
        f"rc={result.returncode!r} expected={expected_rc}",
        f"timed_out={result.timed_out}",
    ]
    if "stdout" in spec:
        if not isinstance(spec["stdout"], str):
            return CheckResult(
                "environment_command", False, "stdout expectation must be a string"
            )
        expected_stdout = _normalise_lineendings(spec["stdout"])
        passed = passed and stdout == expected_stdout
        details.append(f"stdout_exact={stdout == expected_stdout}")
    if spec.get("stderr_empty", False) is not False:
        if spec.get("stderr_empty") is not True:
            return CheckResult(
                "environment_command", False, "stderr_empty must be true or omitted"
            )
        passed = passed and not stderr.strip()
        details.append(f"stderr_empty={not bool(stderr.strip())}")
    return CheckResult(
        "environment_command",
        passed,
        "; ".join(details),
        evidence=f"stdout={stdout[:500]!r}; stderr={stderr[:500]!r}",
    )


def _norm(path: object) -> str:
    p = str(path).replace("\\", "/").strip()
    return p[2:] if p.startswith("./") else p


def _is_ignored(rel_path: str) -> bool:
    """True if the path is a Python import-cache artefact (see module docstring)."""
    parts = rel_path.split("/")
    if any(part in _IGNORE_DIR_NAMES for part in parts):
        return True
    return rel_path.endswith(_IGNORE_FILE_SUFFIXES)


def _non_ignored_files(snap: FilesystemSnapshot) -> set[str]:
    return {p for p in snap.files if not _is_ignored(p)}


# ---------------------------------------------------------------------------
# Snapshot-only checks
# ---------------------------------------------------------------------------


@check("file_exists")
def _file_exists(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    target = _norm(spec["path"])
    ok = target in snap.files
    return CheckResult(
        check_type="file_exists",
        passed=ok,
        detail=(
            f"file {target!r} present"
            if ok
            else f"expected file {target!r} not found"
        ),
        evidence="" if ok else f"{len(snap.files)} files present",
    )


@check("directory_exists")
def _directory_exists(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    target = _norm(spec["path"])
    # A dir is satisfied either by being snapshotted directly or by being an
    # ancestor of an existing file (covers environments that only enumerate
    # files; an empty dir still needs snap.dirs, which is why we track it).
    ok = target in snap.dirs or any(
        f == target or f.startswith(target + "/") for f in snap.files
    )
    return CheckResult(
        check_type="directory_exists",
        passed=ok,
        detail=(
            f"directory {target!r} present"
            if ok
            else f"expected directory {target!r} not found"
        ),
    )


@check("file_is_empty")
def _file_is_empty(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    target = _norm(spec["path"])
    fp = snap.files.get(target)
    if fp is None:
        return CheckResult(
            check_type="file_is_empty",
            passed=False,
            detail=f"file {target!r} not found (cannot be empty)",
        )
    ok = fp.size == 0
    return CheckResult(
        check_type="file_is_empty",
        passed=ok,
        detail=(
            f"file {target!r} is empty"
            if ok
            else f"file {target!r} is {fp.size} bytes, expected 0"
        ),
        evidence=f"size={fp.size}",
    )


@check("file_unchanged")
def _file_unchanged(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Require one file's post-run fingerprint to equal its baseline."""
    target = _norm(spec["path"])
    baseline = spec.get("_snapshot_before")
    if not isinstance(baseline, FilesystemSnapshot):
        return CheckResult(
            check_type="file_unchanged",
            passed=False,
            detail="file_unchanged requires the pre-agent filesystem snapshot",
        )
    before = baseline.files.get(target)
    after = snap.files.get(target)
    if before is None or after is None:
        missing = "baseline" if before is None else "post-run snapshot"
        return CheckResult(
            check_type="file_unchanged",
            passed=False,
            detail=f"file {target!r} missing from {missing}",
        )
    # Content identity is the construct. Requiring an unchanged mtime would
    # make a semantically harmless rewrite fail differently across filesystems.
    ok = before.size == after.size and before.sha256 == after.sha256
    return CheckResult(
        check_type="file_unchanged",
        passed=ok,
        detail=(
            f"file {target!r} is unchanged"
            if ok
            else f"file {target!r} differs from its pre-agent baseline"
        ),
        evidence=(
            ""
            if ok
            else f"before={before.sha256}:{before.size}; after={after.sha256}:{after.size}"
        ),
    )


@check("no_extra_files")
def _no_extra_files(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    # The expected file set is injected by evaluate_checks (derived from the
    # other checks) — a no_extra_files check is meaningless in isolation.
    # __pycache__ / *.pyc are pre-filtered (see module docstring).
    expected: set[str] = set(spec.get("_expected_files", ()))  # type: ignore[arg-type]
    observed = _non_ignored_files(snap)
    extras = sorted(observed - expected)
    ok = not extras
    return CheckResult(
        check_type="no_extra_files",
        passed=ok,
        detail=(
            "no files outside the expected structure"
            if ok
            else f"{len(extras)} unexpected file(s) present"
        ),
        evidence="" if ok else ", ".join(extras[:20]),
    )


def _fnmatch_match(rel_path: str, pattern: str) -> bool:
    """fnmatch on full path OR basename. The basename fallback lets a task
    author write `"*.bak"` and have it catch `lib/foo.bak` without needing
    `**/*.bak` syntax (fnmatch does not span `/`)."""
    return fnmatch.fnmatch(rel_path, pattern) or fnmatch.fnmatch(
        Path(rel_path).name, pattern
    )


@check("no_files_matching")
def _no_files_matching(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail if any non-ignored file matches the given fnmatch glob.

    Used by tasks that need to forbid a class of agent artefacts —
    e.g. `*.bak`, `*_old*`, `refactor-log*` — without having to list
    every possible filename in `required_absent_files`.
    """
    pattern = str(spec.get("pattern", ""))
    if not pattern:
        return CheckResult(
            check_type="no_files_matching",
            passed=False,
            detail="no_files_matching requires a 'pattern' field",
        )
    matches = sorted(p for p in _non_ignored_files(snap) if _fnmatch_match(p, pattern))
    ok = not matches
    return CheckResult(
        check_type="no_files_matching",
        passed=ok,
        detail=(
            f"no files matching {pattern!r}"
            if ok
            else f"{len(matches)} file(s) matching {pattern!r}"
        ),
        evidence="" if ok else ", ".join(matches[:20]),
    )


# ---------------------------------------------------------------------------
# Sandbox-content checks (need _sandbox_host_root)
# ---------------------------------------------------------------------------


def _read_text_for_check(
    rel_path: str, spec: Mapping[str, object], check_name: str
) -> tuple[str | None, CheckResult | None]:
    """Resolve the on-disk content of a sandbox-relative path.

    Returns (content, None) on success, (None, failing CheckResult) on any
    error (missing sandbox root, missing file, unreadable, ignored path).
    Centralising this keeps every content check's failure modes identical.

    Newlines are normalised (\\r\\n / \\r become \\n) before comparison. This
    is intentional — a task author writes the expected content with \\n
    newlines in YAML, and an agent that writes the right bytes but with
    \\r\\n on Windows still passes the byte-content check.

    Encoding is decoded by BOM sniff: UTF-8 (with or without BOM) and
    BOM-marked UTF-16 LE/BE are all accepted. No task prompt constrains
    output encoding, and shell-default encodings differ BY ENVIRONMENT
    (PowerShell 5.1 `>` writes UTF-16LE; `Set-Content -Encoding UTF8`
    writes a BOM; pwsh 7 writes BOM-less UTF-8) — so a strict-UTF-8 read
    would turn encoding into a hidden component of the measured construct
    and concentrate false failures on specific environment arms. Content
    that decodes under none of these fails closed as before.
    """
    if _is_ignored(rel_path):
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=(
                f"{rel_path!r} is an ignored Python cache artefact; "
                "content checks should not target it"
            ),
        )
    host_root = spec.get("_sandbox_host_root")
    if host_root is None:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=(
                f"{check_name} requires the sandbox host root; the runner "
                "must call evaluate_checks(..., sandbox_host_root=...)"
            ),
        )
    file_path = Path(str(host_root)) / rel_path
    if not file_path.is_file():
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=f"file {rel_path!r} not found on disk at {file_path}",
        )
    try:
        raw = file_path.read_bytes()
    except OSError as exc:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=f"file {rel_path!r} not readable: {exc}",
        )
    if raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
        encoding = "utf-16"  # BOM-directed; codec consumes the BOM
    elif raw.startswith(b"\xef\xbb\xbf"):
        encoding = "utf-8-sig"
    else:
        encoding = "utf-8"
    try:
        text = raw.decode(encoding)
    except UnicodeDecodeError as exc:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=f"file {rel_path!r} not decodable as {encoding}: {exc}",
        )
    return text.replace("\r\n", "\n").replace("\r", "\n"), None


@check("python_parses")
def _python_parses(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail if the named file is not syntactically valid Python.

    Used by refactor-style tasks (e.g. C03) where the binary outcome
    requires that every modified .py file still parse — a naive
    find-replace that breaks syntax must register as failure, not success.
    """
    target = _norm(spec["path"])
    content, err = _read_text_for_check(target, spec, "python_parses")
    if err is not None:
        return err
    assert content is not None
    try:
        ast.parse(content)
    except SyntaxError as exc:
        return CheckResult(
            check_type="python_parses",
            passed=False,
            detail=f"file {target!r} does not parse: {exc.msg} at line {exc.lineno}",
            evidence=f"line={exc.lineno} offset={exc.offset}",
        )
    return CheckResult(
        check_type="python_parses",
        passed=True,
        detail=f"file {target!r} parses as valid Python",
    )


@check("file_contains_substring_count")
def _file_contains_substring_count(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless `substring` appears in the file exactly `count` times.

    Substring count (not regex, not token-aware) is deliberate: it lets a
    task YAML pre-register the EXACT post-rename occurrence pattern of an
    identifier (e.g. process_data → process_record), counting BOTH code
    and non-code mentions. The task author works out the expected count
    once from the seed content and the rename spec; the check then verifies
    it deterministically with no rubric coding.
    """
    target = _norm(spec["path"])
    substring_raw = spec.get("substring")
    if not isinstance(substring_raw, str) or substring_raw == "":
        return CheckResult(
            check_type="file_contains_substring_count",
            passed=False,
            detail="file_contains_substring_count requires a non-empty 'substring'",
        )
    expected = spec.get("count")
    if not isinstance(expected, int) or expected < 0:
        return CheckResult(
            check_type="file_contains_substring_count",
            passed=False,
            detail="file_contains_substring_count requires a non-negative integer 'count'",
        )
    content, err = _read_text_for_check(target, spec, "file_contains_substring_count")
    if err is not None:
        return err
    assert content is not None
    actual = content.count(substring_raw)
    ok = actual == expected
    return CheckResult(
        check_type="file_contains_substring_count",
        passed=ok,
        detail=(
            f"file {target!r} contains {substring_raw!r} {actual} time(s) (expected {expected})"
        ),
        evidence=f"actual={actual} expected={expected}",
    )


@check("file_content_equals")
def _file_content_equals(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless file content equals `content` (after newline
    normalisation and encoding sniff; see _read_text_for_check), with
    tolerance for trailing newlines: both sides are compared with
    trailing \\n stripped.

    The tolerance exists because the canonical correct methods disagree
    about the final newline — heredocs, `echo`, and `Set-Content` append
    one; `printf` and Python `write()` don't — and no task prompt pins it
    down. Which trailing-newline convention an agent's tool of choice
    follows is not part of any task's measured construct.

    Used for byte-exact outputs (T03 config.txt, T04 deploy.sh, T06 source
    preservation, C02 answer.txt = '5\\n') and for source-file
    preservation (preconditions content must be unchanged).
    """
    target = _norm(spec["path"])
    expected = spec.get("content")
    if not isinstance(expected, str):
        return CheckResult(
            check_type="file_content_equals",
            passed=False,
            detail="file_content_equals requires a string 'content' field",
        )
    actual, err = _read_text_for_check(target, spec, "file_content_equals")
    if err is not None:
        return err
    assert actual is not None
    # Normalise the EXPECTED side too: a YAML author may write the expected
    # value with literal \r\n, but read_text already normalised the actual
    # side. Normalising both makes comparison symmetric.
    expected_norm = expected.replace("\r\n", "\n").replace("\r", "\n")
    ok = actual.rstrip("\n") == expected_norm.rstrip("\n")
    if ok:
        return CheckResult(
            check_type="file_content_equals",
            passed=True,
            detail=f"file {target!r} content matches expected ({len(expected_norm)} bytes)",
        )
    # Compact mismatch summary — full content would balloon the log; the
    # snapshot already stores hashes for forensic reconstruction.
    diff_at = next(
        (i for i, (a, b) in enumerate(zip(actual, expected_norm)) if a != b),
        min(len(actual), len(expected_norm)),
    )
    return CheckResult(
        check_type="file_content_equals",
        passed=False,
        detail=(
            f"file {target!r} content mismatch: "
            f"actual {len(actual)} bytes, expected {len(expected_norm)} bytes; "
            f"first diverges at byte {diff_at}"
        ),
        evidence=f"actual_len={len(actual)} expected_len={len(expected_norm)} diverge_at={diff_at}",
    )


@check("json_content_equals")
def _json_content_equals(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless file parses as JSON and equals `value` as a Python object.

    Used for outputs where the binary outcome is the STRUCTURE, not the
    bytes — e.g. C05's merged.json, where the task notes explicitly say
    'exactly matches the expected output (modulo whitespace within
    JSON-equivalence)'. Different agents may serialise the same JSON
    differently (inline vs multi-line arrays, key order in some libs),
    and the pre-reg's binary outcome is the semantic content, not the
    serialisation.
    """
    target = _norm(spec["path"])
    if "value" not in spec:
        return CheckResult(
            check_type="json_content_equals",
            passed=False,
            detail="json_content_equals requires a 'value' field",
        )
    expected_value: Any = spec["value"]
    content, err = _read_text_for_check(target, spec, "json_content_equals")
    if err is not None:
        return err
    assert content is not None
    try:
        actual_value = json.loads(content)
    except json.JSONDecodeError as exc:
        return CheckResult(
            check_type="json_content_equals",
            passed=False,
            detail=f"file {target!r} is not valid JSON: {exc.msg} at line {exc.lineno}",
            evidence=f"line={exc.lineno} col={exc.colno}",
        )
    ok = actual_value == expected_value
    return CheckResult(
        check_type="json_content_equals",
        passed=ok,
        detail=(
            f"file {target!r} JSON structure matches expected"
            if ok
            else f"file {target!r} JSON structure does not match expected"
        ),
    )


def _date_from_trial_started_at(raw: object) -> tuple[datetime | None, str | None]:
    """Parse the runner's trial-start timestamp for date-sensitive checks.

    Accepts a `datetime`, a colon-form ISO-8601 string, OR the runner's
    filename-safe stamp — `runner._utc_now()` emits `%Y-%m-%dT%H-%M-%SZ` (dashes
    in the TIME, because the same value names the Windows log file where colons
    are illegal), e.g. ``2026-06-27T01-31-20Z``. That form is NOT
    `fromisoformat`-parseable, so a colon-ISO parse is attempted first and, on
    failure, the leading ``YYYY-MM-DD`` date component — identical in both forms
    and all this check needs — is parsed directly. Without this fallback the
    date-stamped check would error on every real trial (the runner only ever
    produces the dash form)."""
    if raw is None:
        return None, "trial_started_at is required for this date-sensitive check"
    if isinstance(raw, datetime):
        return raw, None
    text = str(raw).strip()
    iso = text[:-1] + "+00:00" if text.endswith("Z") else text
    try:
        return datetime.fromisoformat(iso), None
    except ValueError:
        pass
    try:
        return datetime.strptime(text[:10], "%Y-%m-%d"), None
    except ValueError as exc:
        return None, f"trial_started_at {raw!r} is not date-parseable: {exc}"


@check("file_count_matching")
def _file_count_matching(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless exactly `count` non-ignored files match `pattern`
    (fnmatch) OR `regex` (re), evaluated against the full sandbox-relative
    path. Optional `content_same_as: <other_path>` further requires that
    every matching file have content equal to the referenced file
    (used by T09: backup file content must equal the source).

    `pattern` and `regex` are mutually exclusive. The matcher receives
    the full sandbox-relative POSIX path; for fnmatch a basename fallback
    is also tried (so `"*.tmp"` catches `sub/foo.tmp`). For regex, the
    author anchors with `^...$` if they want full-path equality.
    """
    pattern = spec.get("pattern")
    regex_src = spec.get("regex")
    if (pattern is None) == (regex_src is None):
        return CheckResult(
            check_type="file_count_matching",
            passed=False,
            detail="file_count_matching requires exactly one of 'pattern' or 'regex'",
        )
    expected_count = spec.get("count")
    if not isinstance(expected_count, int) or expected_count < 0:
        return CheckResult(
            check_type="file_count_matching",
            passed=False,
            detail="file_count_matching requires a non-negative integer 'count'",
        )

    candidates = _non_ignored_files(snap)
    if pattern is not None:
        matcher_desc = f"pattern={pattern!r}"
        matches = sorted(p for p in candidates if _fnmatch_match(p, str(pattern)))
    else:
        try:
            compiled = re.compile(str(regex_src))
        except re.error as exc:
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail=f"file_count_matching regex {regex_src!r} did not compile: {exc}",
            )
        matcher_desc = f"regex={regex_src!r}"
        matches = sorted(p for p in candidates if compiled.fullmatch(p))

    if len(matches) != expected_count:
        return CheckResult(
            check_type="file_count_matching",
            passed=False,
            detail=(
                f"{len(matches)} file(s) match {matcher_desc} "
                f"(expected {expected_count})"
            ),
            evidence=", ".join(matches[:20]),
        )

    # Optional: dynamic date-stamped filenames. The regex must expose a named
    # date group; the observed date is compared to the trial-start date. A
    # small tolerance handles env-local dates when the runner records UTC.
    date_equals = spec.get("date_equals")
    if date_equals is not None:
        if date_equals != "trial_started_at":
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail=(
                    "file_count_matching date_equals currently supports only "
                    "'trial_started_at'"
                ),
            )
        if pattern is not None:
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail="date_equals requires a regex with a named date_group",
            )
        # `compiled` is the regex already built in the regex branch above —
        # date_equals only reaches here with pattern is None (rejected just
        # above), so the regex path ran and `compiled` is in scope.
        group = str(spec.get("date_group", "date"))
        trial_dt, err = _date_from_trial_started_at(spec.get("_trial_started_at"))
        if err is not None:
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail=f"file_count_matching date comparison failed: {err}",
            )
        assert trial_dt is not None
        try:
            tolerance = int(spec.get("date_tolerance_days", 0))
        except (TypeError, ValueError):
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail="date_tolerance_days must be an integer",
            )
        if tolerance < 0:
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail="date_tolerance_days must be non-negative",
            )
        date_format = str(spec.get("date_format", "%Y-%m-%d"))
        allowed = {
            (trial_dt + timedelta(days=offset)).strftime(date_format)
            for offset in range(-tolerance, tolerance + 1)
        }
        for match_rel in matches:
            match = compiled.fullmatch(match_rel)
            observed = match.groupdict().get(group) if match else None
            if observed not in allowed:
                return CheckResult(
                    check_type="file_count_matching",
                    passed=False,
                    detail=(
                        f"matched file {match_rel!r} has {group}={observed!r}; "
                        f"expected one of {sorted(allowed)!r}"
                    ),
                )

    # Optional: content equivalence to a reference file.
    content_same_as = spec.get("content_same_as")
    if content_same_as is not None:
        ref_rel = _norm(content_same_as)
        ref_content, ref_err = _read_text_for_check(
            ref_rel, spec, "file_count_matching"
        )
        if ref_err is not None:
            # Re-tag the inner error so the failure clearly attributes to
            # the reference-resolution step rather than the matched file.
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail=(
                    "file_count_matching content_same_as reference unreadable: "
                    + ref_err.detail
                ),
            )
        assert ref_content is not None
        for match_rel in matches:
            match_content, match_err = _read_text_for_check(
                match_rel, spec, "file_count_matching"
            )
            if match_err is not None:
                return CheckResult(
                    check_type="file_count_matching",
                    passed=False,
                    detail=(
                        f"file_count_matching matched file {match_rel!r} unreadable: "
                        + match_err.detail
                    ),
                )
            if match_content != ref_content:
                return CheckResult(
                    check_type="file_count_matching",
                    passed=False,
                    detail=(
                        f"matched file {match_rel!r} content differs from "
                        f"reference {ref_rel!r}"
                    ),
                )

    return CheckResult(
        check_type="file_count_matching",
        passed=True,
        detail=(
            f"{len(matches)} file(s) match {matcher_desc} "
            f"(expected {expected_count})"
            + (
                f"; content equals {_norm(content_same_as)!r}"
                if content_same_as is not None
                else ""
            )
        ),
    )


# ---------------------------------------------------------------------------
# Agent-trace checks (need _agent_commands)
# ---------------------------------------------------------------------------


def _agent_commands_or_failure(
    spec: Mapping[str, object], check_name: str
) -> tuple[Sequence[Any] | None, CheckResult | None]:
    """Return (commands, None) or (None, fail) — analogue of _read_text_for_check."""
    commands = spec.get("_agent_commands")
    if commands is None:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=(
                f"{check_name} requires the agent command trace; the runner "
                "must call evaluate_checks(..., agent_commands=...)"
            ),
        )
    return commands, None  # type: ignore[return-value]


def _normalise_lineendings(s: str) -> str:
    return s.replace("\r\n", "\n").replace("\r", "\n")


def _strip_shell_comments(command: str) -> str:
    """Remove comment text from a command before command-text constraints.

    A command can carry constraint tokens inside a comment
    (`"..." <# app.log #>` or `"..." # run.ps1`) without touching the
    target at all, so constraints must see only the non-comment text.
    Handles PowerShell block comments (<# ... #>) and #-to-end-of-line in
    both PowerShell and POSIX shells. A # inside single or double quotes
    is content; a # not at the start of a word (e.g. bash `${#var}`) is
    content too.
    """
    text = re.sub(r"<#.*?#>", " ", command, flags=re.DOTALL)
    out: list[str] = []
    quote: str | None = None
    i = 0
    while i < len(text):
        ch = text[i]
        if quote is None and ch in "'\"":
            quote = ch
        elif quote == ch:
            quote = None
        elif (
            quote is None
            and ch == "#"
            and (i == 0 or text[i - 1] in " \t\n;|&(")
        ):
            nl = text.find("\n", i)
            if nl == -1:
                break
            i = nl
            continue
        out.append(ch)
        i += 1
    return "".join(out)


@check("agent_any_command_stdout_equals")
def _agent_any_command_stdout_equals(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless AT LEAST ONE command the agent issued produced a stdout
    that, after newline normalisation and trailing-newline strip on both
    sides, equals `expected`.

    'Any command' rather than 'last command' is deliberate: a sensible
    agent may verify its own work after the answer-producing command, and
    the pre-reg should not penalise that. The expected stdout is the
    agent's answer to the prompt; a verifying command's stdout is allowed
    to differ.

    Trailing newlines are stripped because agent CLIs disagree with the
    YAML convention here: the real recorded Claude Code capture
    (tests/fixtures/claude_code_streamjson_C01.jsonl) shows the CLI trims
    the final newline from tool_use_result stdout, while every YAML
    `expected` block ends with one. Exact comparison would fail every
    real trial on stdout tasks regardless of agent behaviour.

    Command-text constraints (`command_contains`, `command_regex`,
    `command_not_regex`) are applied to the command with comment text
    removed (see _strip_shell_comments) — otherwise `"..." # app.log`
    satisfies a contains-constraint without touching the target.

    `require_empty_stderr: true` additionally requires the matching
    command's own stderr to be empty. This is the per-command form of the
    pre-registered `required_final_stderr_exact: ""` predicate: it scores
    the answer-producing command, so an agent that triggers the seeded
    error (stderr noise on an early attempt) and then recovers cleanly
    still passes — recovery is task completion, not failure.
    """
    expected = spec.get("expected")
    if not isinstance(expected, str):
        return CheckResult(
            check_type="agent_any_command_stdout_equals",
            passed=False,
            detail="agent_any_command_stdout_equals requires a string 'expected' field",
        )

    command_contains_raw = spec.get("command_contains", [])
    if isinstance(command_contains_raw, str):
        command_contains = [command_contains_raw]
    else:
        command_contains = list(command_contains_raw or [])  # type: ignore[arg-type]
    if not all(isinstance(s, str) and s for s in command_contains):
        return CheckResult(
            check_type="agent_any_command_stdout_equals",
            passed=False,
            detail="command_contains must be a string or list of non-empty strings",
        )
    command_regex = spec.get("command_regex")
    command_pattern = None
    if command_regex is not None:
        try:
            command_pattern = re.compile(str(command_regex))
        except re.error as exc:
            return CheckResult(
                check_type="agent_any_command_stdout_equals",
                passed=False,
                detail=f"command_regex {command_regex!r} did not compile: {exc}",
            )
    command_not_regex = spec.get("command_not_regex")
    command_forbid_pattern = None
    if command_not_regex is not None:
        try:
            command_forbid_pattern = re.compile(str(command_not_regex))
        except re.error as exc:
            return CheckResult(
                check_type="agent_any_command_stdout_equals",
                passed=False,
                detail=f"command_not_regex {command_not_regex!r} did not compile: {exc}",
            )

    require_empty_stderr = bool(spec.get("require_empty_stderr", False))

    commands, err = _agent_commands_or_failure(spec, "agent_any_command_stdout_equals")
    if err is not None:
        return err
    assert commands is not None
    expected_norm = _normalise_lineendings(expected).rstrip("\n")
    stdout_matches = 0
    constrained_out = 0
    for cmd in commands:
        actual = _normalise_lineendings(getattr(cmd, "stdout", "") or "").rstrip("\n")
        if actual != expected_norm:
            continue
        stdout_matches += 1
        command_text = _strip_shell_comments(str(getattr(cmd, "command", "") or ""))
        if command_contains and not all(s in command_text for s in command_contains):
            continue
        if command_pattern is not None and not command_pattern.search(command_text):
            continue
        if command_forbid_pattern is not None and command_forbid_pattern.search(command_text):
            continue
        constrained_out += 1
        if require_empty_stderr:
            stderr_text = _normalise_lineendings(
                getattr(cmd, "stderr", "") or ""
            ).strip()
            if stderr_text:
                continue
        return CheckResult(
            check_type="agent_any_command_stdout_equals",
            passed=True,
            detail=(
                f"command #{getattr(cmd, 'index', '?')} stdout "
                f"matches expected ({len(expected_norm)} bytes)"
            ),
        )
    constraint_detail = ""
    if stdout_matches:
        constraint_detail = (
            f"; {stdout_matches} command(s) had matching stdout but failed "
            "command-text constraints"
        )
        if constrained_out:
            constraint_detail = (
                f"; {constrained_out} command(s) matched stdout and "
                "command-text constraints but wrote to stderr"
            )
    return CheckResult(
        check_type="agent_any_command_stdout_equals",
        passed=False,
        detail=(
            f"no command among {len(commands)} produced stdout matching the "
            f"expected {len(expected_norm)}-byte answer"
            f"{constraint_detail}"
        ),
        evidence=f"commands_seen={len(commands)}",
    )


@check("agent_all_command_stderrs_empty")
def _agent_all_command_stderrs_empty(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail if ANY command the agent issued produced non-empty stderr
    (after newline normalisation and surrounding-whitespace strip).

    No task uses this as of 2026-07-03: T06/T08 moved to
    `require_empty_stderr` on the stdout check, which scopes the stderr
    requirement to the answer-producing command — the all-commands form
    scored a fire-then-recover trajectory as H1 failure (see
    DEVIATIONS.md). Retained for tasks whose intent genuinely is
    "no command may ever write to stderr". A vacuous pass on an empty
    command list is intentionally permissive — pair it with a check
    that fails a no-op trial.
    """
    commands, err = _agent_commands_or_failure(spec, "agent_all_command_stderrs_empty")
    if err is not None:
        return err
    assert commands is not None
    noisy: list[tuple[Any, str]] = []
    for cmd in commands:
        actual = _normalise_lineendings(getattr(cmd, "stderr", "") or "").strip()
        if actual:
            noisy.append((getattr(cmd, "index", "?"), actual))
    if not noisy:
        return CheckResult(
            check_type="agent_all_command_stderrs_empty",
            passed=True,
            detail=f"all {len(commands)} command stderrs are empty",
        )
    return CheckResult(
        check_type="agent_all_command_stderrs_empty",
        passed=False,
        detail=f"{len(noisy)} of {len(commands)} command(s) wrote to stderr",
        evidence="; ".join(
            f"#{idx}: {text[:120]}" for idx, text in noisy[:5]
        ),
    )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def _expected_files_from(specs: Sequence[Mapping[str, object]]) -> set[str]:
    """Files a successful run must contain — i.e. every path asserted by an
    existence/content/parse/count check. Used to give no_extra_files its
    baseline so it means 'nothing the task did not ask for'."""
    out: set[str] = set()
    asserting_types = {
        "file_exists",
        "file_is_empty",
        "file_unchanged",
        "python_parses",
        "file_contains_substring_count",
        "file_content_equals",
        "json_content_equals",
    }
    for s in specs:
        if s.get("type") in asserting_types and "path" in s:
            out.add(_norm(s["path"]))
    return out


def evaluate_checks(
    snap: FilesystemSnapshot,
    specs: Sequence[Mapping[str, object]],
    *,
    sandbox_host_root: Path | str | None = None,
    agent_commands: Sequence[Any] | None = None,
    trial_started_at: object | None = None,
    environment_exec: Callable[..., Any] | None = None,
    environment_cwd: str | None = None,
    snapshot_before: FilesystemSnapshot | None = None,
    stop_on_failure: bool = False,
) -> tuple[bool, list[CheckResult]]:
    """Run every check. Returns (overall_success, per-check results).

    overall_success is the AND of all checks — the trial's binary outcome.
    An unknown check type fails closed (returns a failing CheckResult rather
    than raising): a typo in a task YAML must not silently pass a trial.

    `sandbox_host_root` is the host-side path to the trial's sandbox. It is
    forwarded into content-based check specs (see _CONTEXT_CHECKS).
    `agent_commands` is the per-command transcript; it is forwarded into
    agent-trace check specs (see _AGENT_CHECKS). Snapshot-only checks
    ignore both. `trial_started_at` is forwarded to context checks that need
    dynamic, trial-start-relative expectations such as dated filenames.
    `snapshot_before` is forwarded to baseline-relative checks.
    `stop_on_failure` is reserved for qualification probes that only need to
    establish that an untouched fixture fails. Normal trial evaluation leaves
    it false and records every check result.
    """
    expected = _expected_files_from(specs)
    results: list[CheckResult] = []
    for spec in specs:
        ctype = str(spec.get("type", ""))
        fn = _REGISTRY.get(ctype)
        if fn is None:
            results.append(
                CheckResult(
                    check_type=ctype or "<missing>",
                    passed=False,
                    detail=f"unknown check type {ctype!r} — fix the task YAML",
                )
            )
            if stop_on_failure:
                break
            continue
        if ctype == "no_extra_files":
            spec = {**spec, "_expected_files": tuple(expected)}
        elif ctype in _CONTEXT_CHECKS:
            spec = {
                **spec,
                "_sandbox_host_root": sandbox_host_root,
                "_trial_started_at": trial_started_at,
            }
        elif ctype in _AGENT_CHECKS:
            spec = {**spec, "_agent_commands": agent_commands}
        elif ctype in _ENVIRONMENT_CHECKS:
            spec = {
                **spec,
                "_environment_exec": environment_exec,
                "_environment_cwd": environment_cwd,
            }
        elif ctype in _BASELINE_CHECKS:
            spec = {**spec, "_snapshot_before": snapshot_before}
        results.append(fn(snap, spec))
        if stop_on_failure and not results[-1].passed:
            break
    overall = all(r.passed for r in results)
    return overall, results
