"""Success-check executors.

A task YAML lists `success_checks`; ALL must pass for the trial to count as
a success (the binary primary outcome behind H1). Three families of check
exist, distinguished by what they read:

  * Snapshot-only — pure functions of the post-run FilesystemSnapshot:
    file_exists, directory_exists, file_is_empty, no_extra_files,
    no_files_matching.

  * Sandbox-content — read file bytes from the host filesystem. They need
    the sandbox host root, supplied via `evaluate_checks(...,
    sandbox_host_root=...)`. If it is not provided they fail closed:
    python_parses, file_contains_substring_count, file_content_equals,
    json_content_equals, file_count_matching.

  * Agent-trace — read the per-command stdout / stderr the agent issued
    during the trial. They need the agent's CommandRecord list, supplied
    via `evaluate_checks(..., agent_commands=...)`. If it is not provided
    they fail closed: agent_any_command_stdout_equals,
    agent_all_command_stderrs_empty.

Adding a new check type = add one function + one `@check("name")` + (if
the check needs context) one entry in `_CONTEXT_CHECKS` or
`_AGENT_CHECKS`. The runner calls `evaluate_checks` and never needs to
know the catalogue.

Path convention: all paths are sandbox-relative POSIX, matching
`FilesystemSnapshot`. A leading "./" in the YAML is tolerated and stripped.

Ignored artefacts: `__pycache__/` directories and `.pyc` / `.pyo` / `.pyd`
files are excluded from `no_extra_files` / `no_files_matching` /
`file_count_matching` and are never the target of a content check. They
are import-side-effect artefacts of any Python verification step (e.g.
an agent that runs `python -c "import lib"` to sanity-check its work).
Counting them as "extras" would penalise the more diligent agent — a
denominator-bias failure mode the pre-registration explicitly avoids.
"""

from __future__ import annotations

import ast
import fnmatch
import json
import re
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import Any

from .types import CheckResult, FilesystemSnapshot

CheckFn = Callable[[FilesystemSnapshot, Mapping[str, object]], CheckResult]

_REGISTRY: dict[str, CheckFn] = {}

# Python import-cache artefacts. Generated by ANY `python -c "import ..."`
# verification an agent may run; would otherwise spuriously fail
# no_extra_files / no_files_matching / file_count_matching. Listed here,
# not per-task, so the rule is uniform and auditable.
_IGNORE_DIR_NAMES: frozenset[str] = frozenset({
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
})
_IGNORE_FILE_SUFFIXES: tuple[str, ...] = (".pyc", ".pyo", ".pyd")

# Check types that need to read file content from the host filesystem.
# evaluate_checks injects the sandbox host root into these specs.
_CONTEXT_CHECKS: frozenset[str] = frozenset({
    "python_parses",
    "file_contains_substring_count",
    "file_content_equals",
    "json_content_equals",
    "file_count_matching",
})

# Check types that need the agent's per-command transcript.
# evaluate_checks injects the agent_commands sequence into these specs.
_AGENT_CHECKS: frozenset[str] = frozenset({
    "agent_any_command_stdout_equals",
    "agent_all_command_stderrs_empty",
})


def _norm(path: object) -> str:
    p = str(path).replace("\\", "/").strip()
    return p[2:] if p.startswith("./") else p


def _is_ignored(rel_path: str) -> bool:
    """True if the path is a Python import-cache artefact (see module docstring)."""
    parts = rel_path.split("/")
    if any(part in _IGNORE_DIR_NAMES for part in parts):
        return True
    return rel_path.endswith(_IGNORE_FILE_SUFFIXES)


def _non_ignored_files(snap: FilesystemSnapshot) -> set[str]:
    return {p for p in snap.files if not _is_ignored(p)}


def check(name: str) -> Callable[[CheckFn], CheckFn]:
    def register(fn: CheckFn) -> CheckFn:
        _REGISTRY[name] = fn
        return fn

    return register


# ---------------------------------------------------------------------------
# Snapshot-only checks
# ---------------------------------------------------------------------------


@check("file_exists")
def _file_exists(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    target = _norm(spec["path"])
    ok = target in snap.files
    return CheckResult(
        check_type="file_exists",
        passed=ok,
        detail=(
            f"file {target!r} present"
            if ok
            else f"expected file {target!r} not found"
        ),
        evidence="" if ok else f"{len(snap.files)} files present",
    )


@check("directory_exists")
def _directory_exists(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    target = _norm(spec["path"])
    # A dir is satisfied either by being snapshotted directly or by being an
    # ancestor of an existing file (covers environments that only enumerate
    # files; an empty dir still needs snap.dirs, which is why we track it).
    ok = target in snap.dirs or any(
        f == target or f.startswith(target + "/") for f in snap.files
    )
    return CheckResult(
        check_type="directory_exists",
        passed=ok,
        detail=(
            f"directory {target!r} present"
            if ok
            else f"expected directory {target!r} not found"
        ),
    )


@check("file_is_empty")
def _file_is_empty(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    target = _norm(spec["path"])
    fp = snap.files.get(target)
    if fp is None:
        return CheckResult(
            check_type="file_is_empty",
            passed=False,
            detail=f"file {target!r} not found (cannot be empty)",
        )
    ok = fp.size == 0
    return CheckResult(
        check_type="file_is_empty",
        passed=ok,
        detail=(
            f"file {target!r} is empty"
            if ok
            else f"file {target!r} is {fp.size} bytes, expected 0"
        ),
        evidence=f"size={fp.size}",
    )


@check("no_extra_files")
def _no_extra_files(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    # The expected file set is injected by evaluate_checks (derived from the
    # other checks) — a no_extra_files check is meaningless in isolation.
    # __pycache__ / *.pyc are pre-filtered (see module docstring).
    expected: set[str] = set(spec.get("_expected_files", ()))  # type: ignore[arg-type]
    observed = _non_ignored_files(snap)
    extras = sorted(observed - expected)
    ok = not extras
    return CheckResult(
        check_type="no_extra_files",
        passed=ok,
        detail=(
            "no files outside the expected structure"
            if ok
            else f"{len(extras)} unexpected file(s) present"
        ),
        evidence="" if ok else ", ".join(extras[:20]),
    )


def _fnmatch_match(rel_path: str, pattern: str) -> bool:
    """fnmatch on full path OR basename. The basename fallback lets a task
    author write `"*.bak"` and have it catch `lib/foo.bak` without needing
    `**/*.bak` syntax (fnmatch does not span `/`)."""
    return fnmatch.fnmatch(rel_path, pattern) or fnmatch.fnmatch(
        Path(rel_path).name, pattern
    )


@check("no_files_matching")
def _no_files_matching(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail if any non-ignored file matches the given fnmatch glob.

    Used by tasks that need to forbid a class of agent artefacts —
    e.g. `*.bak`, `*_old*`, `refactor-log*` — without having to list
    every possible filename in `required_absent_files`.
    """
    pattern = str(spec.get("pattern", ""))
    if not pattern:
        return CheckResult(
            check_type="no_files_matching",
            passed=False,
            detail="no_files_matching requires a 'pattern' field",
        )
    matches = sorted(p for p in _non_ignored_files(snap) if _fnmatch_match(p, pattern))
    ok = not matches
    return CheckResult(
        check_type="no_files_matching",
        passed=ok,
        detail=(
            f"no files matching {pattern!r}"
            if ok
            else f"{len(matches)} file(s) matching {pattern!r}"
        ),
        evidence="" if ok else ", ".join(matches[:20]),
    )


# ---------------------------------------------------------------------------
# Sandbox-content checks (need _sandbox_host_root)
# ---------------------------------------------------------------------------


def _read_text_for_check(
    rel_path: str, spec: Mapping[str, object], check_name: str
) -> tuple[str | None, CheckResult | None]:
    """Resolve the on-disk content of a sandbox-relative path.

    Returns (content, None) on success, (None, failing CheckResult) on any
    error (missing sandbox root, missing file, unreadable, ignored path).
    Centralising this keeps every content check's failure modes identical.

    `read_text` with default newline=None enables universal-newlines
    translation: \\r\\n / \\r are normalised to \\n before comparison. This
    is intentional — a task author writes the expected content with \\n
    newlines in YAML, and an agent that writes the right bytes but with
    \\r\\n on Windows still passes the byte-content check.
    """
    if _is_ignored(rel_path):
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=(
                f"{rel_path!r} is an ignored Python cache artefact; "
                "content checks should not target it"
            ),
        )
    host_root = spec.get("_sandbox_host_root")
    if host_root is None:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=(
                f"{check_name} requires the sandbox host root; the runner "
                "must call evaluate_checks(..., sandbox_host_root=...)"
            ),
        )
    file_path = Path(str(host_root)) / rel_path
    if not file_path.is_file():
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=f"file {rel_path!r} not found on disk at {file_path}",
        )
    try:
        return file_path.read_text(encoding="utf-8"), None
    except (OSError, UnicodeDecodeError) as exc:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=f"file {rel_path!r} not readable as UTF-8: {exc}",
        )


@check("python_parses")
def _python_parses(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail if the named file is not syntactically valid Python.

    Used by refactor-style tasks (e.g. C03) where the binary outcome
    requires that every modified .py file still parse — a naive
    find-replace that breaks syntax must register as failure, not success.
    """
    target = _norm(spec["path"])
    content, err = _read_text_for_check(target, spec, "python_parses")
    if err is not None:
        return err
    assert content is not None
    try:
        ast.parse(content)
    except SyntaxError as exc:
        return CheckResult(
            check_type="python_parses",
            passed=False,
            detail=f"file {target!r} does not parse: {exc.msg} at line {exc.lineno}",
            evidence=f"line={exc.lineno} offset={exc.offset}",
        )
    return CheckResult(
        check_type="python_parses",
        passed=True,
        detail=f"file {target!r} parses as valid Python",
    )


@check("file_contains_substring_count")
def _file_contains_substring_count(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless `substring` appears in the file exactly `count` times.

    Substring count (not regex, not token-aware) is deliberate: it lets a
    task YAML pre-register the EXACT post-rename occurrence pattern of an
    identifier (e.g. process_data → process_record), counting BOTH code
    and non-code mentions. The task author works out the expected count
    once from the seed content and the rename spec; the check then verifies
    it deterministically with no rubric coding.
    """
    target = _norm(spec["path"])
    substring_raw = spec.get("substring")
    if not isinstance(substring_raw, str) or substring_raw == "":
        return CheckResult(
            check_type="file_contains_substring_count",
            passed=False,
            detail="file_contains_substring_count requires a non-empty 'substring'",
        )
    expected = spec.get("count")
    if not isinstance(expected, int) or expected < 0:
        return CheckResult(
            check_type="file_contains_substring_count",
            passed=False,
            detail="file_contains_substring_count requires a non-negative integer 'count'",
        )
    content, err = _read_text_for_check(target, spec, "file_contains_substring_count")
    if err is not None:
        return err
    assert content is not None
    actual = content.count(substring_raw)
    ok = actual == expected
    return CheckResult(
        check_type="file_contains_substring_count",
        passed=ok,
        detail=(
            f"file {target!r} contains {substring_raw!r} {actual} time(s) (expected {expected})"
        ),
        evidence=f"actual={actual} expected={expected}",
    )


@check("file_content_equals")
def _file_content_equals(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless file content equals `content` exactly (after universal-
    newlines normalisation; see _read_text_for_check).

    Used for byte-exact outputs (T03 config.txt, T04 deploy.sh, T06 source
    preservation, C02 answer.txt = '5\\n') and for source-file
    preservation (preconditions content must be unchanged).
    """
    target = _norm(spec["path"])
    expected = spec.get("content")
    if not isinstance(expected, str):
        return CheckResult(
            check_type="file_content_equals",
            passed=False,
            detail="file_content_equals requires a string 'content' field",
        )
    actual, err = _read_text_for_check(target, spec, "file_content_equals")
    if err is not None:
        return err
    assert actual is not None
    # Normalise the EXPECTED side too: a YAML author may write the expected
    # value with literal \r\n, but read_text already normalised the actual
    # side. Normalising both makes comparison symmetric.
    expected_norm = expected.replace("\r\n", "\n").replace("\r", "\n")
    ok = actual == expected_norm
    if ok:
        return CheckResult(
            check_type="file_content_equals",
            passed=True,
            detail=f"file {target!r} content matches expected ({len(expected_norm)} bytes)",
        )
    # Compact mismatch summary — full content would balloon the log; the
    # snapshot already stores hashes for forensic reconstruction.
    diff_at = next(
        (i for i, (a, b) in enumerate(zip(actual, expected_norm)) if a != b),
        min(len(actual), len(expected_norm)),
    )
    return CheckResult(
        check_type="file_content_equals",
        passed=False,
        detail=(
            f"file {target!r} content mismatch: "
            f"actual {len(actual)} bytes, expected {len(expected_norm)} bytes; "
            f"first diverges at byte {diff_at}"
        ),
        evidence=f"actual_len={len(actual)} expected_len={len(expected_norm)} diverge_at={diff_at}",
    )


@check("json_content_equals")
def _json_content_equals(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless file parses as JSON and equals `value` as a Python object.

    Used for outputs where the binary outcome is the STRUCTURE, not the
    bytes — e.g. C05's merged.json, where the task notes explicitly say
    'exactly matches the expected output (modulo whitespace within
    JSON-equivalence)'. Different agents may serialise the same JSON
    differently (inline vs multi-line arrays, key order in some libs),
    and the pre-reg's binary outcome is the semantic content, not the
    serialisation.
    """
    target = _norm(spec["path"])
    if "value" not in spec:
        return CheckResult(
            check_type="json_content_equals",
            passed=False,
            detail="json_content_equals requires a 'value' field",
        )
    expected_value: Any = spec["value"]
    content, err = _read_text_for_check(target, spec, "json_content_equals")
    if err is not None:
        return err
    assert content is not None
    try:
        actual_value = json.loads(content)
    except json.JSONDecodeError as exc:
        return CheckResult(
            check_type="json_content_equals",
            passed=False,
            detail=f"file {target!r} is not valid JSON: {exc.msg} at line {exc.lineno}",
            evidence=f"line={exc.lineno} col={exc.colno}",
        )
    ok = actual_value == expected_value
    return CheckResult(
        check_type="json_content_equals",
        passed=ok,
        detail=(
            f"file {target!r} JSON structure matches expected"
            if ok
            else f"file {target!r} JSON structure does not match expected"
        ),
    )


@check("file_count_matching")
def _file_count_matching(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless exactly `count` non-ignored files match `pattern`
    (fnmatch) OR `regex` (re), evaluated against the full sandbox-relative
    path. Optional `content_same_as: <other_path>` further requires that
    every matching file have content equal to the referenced file
    (used by T09: backup file content must equal the source).

    `pattern` and `regex` are mutually exclusive. The matcher receives
    the full sandbox-relative POSIX path; for fnmatch a basename fallback
    is also tried (so `"*.tmp"` catches `sub/foo.tmp`). For regex, the
    author anchors with `^...$` if they want full-path equality.
    """
    pattern = spec.get("pattern")
    regex_src = spec.get("regex")
    if (pattern is None) == (regex_src is None):
        return CheckResult(
            check_type="file_count_matching",
            passed=False,
            detail="file_count_matching requires exactly one of 'pattern' or 'regex'",
        )
    expected_count = spec.get("count")
    if not isinstance(expected_count, int) or expected_count < 0:
        return CheckResult(
            check_type="file_count_matching",
            passed=False,
            detail="file_count_matching requires a non-negative integer 'count'",
        )

    candidates = _non_ignored_files(snap)
    if pattern is not None:
        matcher_desc = f"pattern={pattern!r}"
        matches = sorted(p for p in candidates if _fnmatch_match(p, str(pattern)))
    else:
        try:
            compiled = re.compile(str(regex_src))
        except re.error as exc:
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail=f"file_count_matching regex {regex_src!r} did not compile: {exc}",
            )
        matcher_desc = f"regex={regex_src!r}"
        matches = sorted(p for p in candidates if compiled.fullmatch(p))

    if len(matches) != expected_count:
        return CheckResult(
            check_type="file_count_matching",
            passed=False,
            detail=(
                f"{len(matches)} file(s) match {matcher_desc} "
                f"(expected {expected_count})"
            ),
            evidence=", ".join(matches[:20]),
        )

    # Optional: content equivalence to a reference file.
    content_same_as = spec.get("content_same_as")
    if content_same_as is not None:
        ref_rel = _norm(content_same_as)
        ref_content, ref_err = _read_text_for_check(
            ref_rel, spec, "file_count_matching"
        )
        if ref_err is not None:
            # Re-tag the inner error so the failure clearly attributes to
            # the reference-resolution step rather than the matched file.
            return CheckResult(
                check_type="file_count_matching",
                passed=False,
                detail=(
                    "file_count_matching content_same_as reference unreadable: "
                    + ref_err.detail
                ),
            )
        assert ref_content is not None
        for match_rel in matches:
            match_content, match_err = _read_text_for_check(
                match_rel, spec, "file_count_matching"
            )
            if match_err is not None:
                return CheckResult(
                    check_type="file_count_matching",
                    passed=False,
                    detail=(
                        f"file_count_matching matched file {match_rel!r} unreadable: "
                        + match_err.detail
                    ),
                )
            if match_content != ref_content:
                return CheckResult(
                    check_type="file_count_matching",
                    passed=False,
                    detail=(
                        f"matched file {match_rel!r} content differs from "
                        f"reference {ref_rel!r}"
                    ),
                )

    return CheckResult(
        check_type="file_count_matching",
        passed=True,
        detail=(
            f"{len(matches)} file(s) match {matcher_desc} "
            f"(expected {expected_count})"
            + (
                f"; content equals {_norm(content_same_as)!r}"
                if content_same_as is not None
                else ""
            )
        ),
    )


# ---------------------------------------------------------------------------
# Agent-trace checks (need _agent_commands)
# ---------------------------------------------------------------------------


def _agent_commands_or_failure(
    spec: Mapping[str, object], check_name: str
) -> tuple[Sequence[Any] | None, CheckResult | None]:
    """Return (commands, None) or (None, fail) — analogue of _read_text_for_check."""
    commands = spec.get("_agent_commands")
    if commands is None:
        return None, CheckResult(
            check_type=check_name,
            passed=False,
            detail=(
                f"{check_name} requires the agent command trace; the runner "
                "must call evaluate_checks(..., agent_commands=...)"
            ),
        )
    return commands, None  # type: ignore[return-value]


def _normalise_lineendings(s: str) -> str:
    return s.replace("\r\n", "\n").replace("\r", "\n")


@check("agent_any_command_stdout_equals")
def _agent_any_command_stdout_equals(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail unless AT LEAST ONE command the agent issued produced a stdout
    that, after newline normalisation, exactly equals `expected`.

    'Any command' rather than 'last command' is deliberate: a sensible
    agent may verify its own work after the answer-producing command, and
    the pre-reg should not penalise that. The expected stdout is the
    agent's answer to the prompt; a verifying command's stdout is allowed
    to differ.
    """
    expected = spec.get("expected")
    if not isinstance(expected, str):
        return CheckResult(
            check_type="agent_any_command_stdout_equals",
            passed=False,
            detail="agent_any_command_stdout_equals requires a string 'expected' field",
        )
    commands, err = _agent_commands_or_failure(spec, "agent_any_command_stdout_equals")
    if err is not None:
        return err
    assert commands is not None
    expected_norm = _normalise_lineendings(expected)
    for cmd in commands:
        actual = _normalise_lineendings(getattr(cmd, "stdout", "") or "")
        if actual == expected_norm:
            return CheckResult(
                check_type="agent_any_command_stdout_equals",
                passed=True,
                detail=(
                    f"command #{getattr(cmd, 'index', '?')} stdout "
                    f"matches expected ({len(expected_norm)} bytes)"
                ),
            )
    return CheckResult(
        check_type="agent_any_command_stdout_equals",
        passed=False,
        detail=(
            f"no command among {len(commands)} produced stdout matching the "
            f"expected {len(expected_norm)}-byte answer"
        ),
        evidence=f"commands_seen={len(commands)}",
    )


@check("agent_all_command_stderrs_empty")
def _agent_all_command_stderrs_empty(
    snap: FilesystemSnapshot, spec: Mapping[str, object]
) -> CheckResult:
    """Fail if ANY command the agent issued produced non-empty stderr
    (after newline normalisation and surrounding-whitespace strip).

    Used by tasks (T06, T08) whose binary outcome requires no error
    output. A vacuous pass on an empty command list is intentionally
    permissive — the accompanying agent_any_command_stdout_equals will
    fail a no-op trial, so this check does not need to.
    """
    commands, err = _agent_commands_or_failure(spec, "agent_all_command_stderrs_empty")
    if err is not None:
        return err
    assert commands is not None
    noisy: list[tuple[Any, str]] = []
    for cmd in commands:
        actual = _normalise_lineendings(getattr(cmd, "stderr", "") or "").strip()
        if actual:
            noisy.append((getattr(cmd, "index", "?"), actual))
    if not noisy:
        return CheckResult(
            check_type="agent_all_command_stderrs_empty",
            passed=True,
            detail=f"all {len(commands)} command stderrs are empty",
        )
    return CheckResult(
        check_type="agent_all_command_stderrs_empty",
        passed=False,
        detail=f"{len(noisy)} of {len(commands)} command(s) wrote to stderr",
        evidence="; ".join(
            f"#{idx}: {text[:120]}" for idx, text in noisy[:5]
        ),
    )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def _expected_files_from(specs: Sequence[Mapping[str, object]]) -> set[str]:
    """Files a successful run must contain — i.e. every path asserted by an
    existence/content/parse/count check. Used to give no_extra_files its
    baseline so it means 'nothing the task did not ask for'."""
    out: set[str] = set()
    asserting_types = {
        "file_exists",
        "file_is_empty",
        "python_parses",
        "file_contains_substring_count",
        "file_content_equals",
        "json_content_equals",
    }
    for s in specs:
        if s.get("type") in asserting_types and "path" in s:
            out.add(_norm(s["path"]))
    return out


def evaluate_checks(
    snap: FilesystemSnapshot,
    specs: Sequence[Mapping[str, object]],
    *,
    sandbox_host_root: Path | str | None = None,
    agent_commands: Sequence[Any] | None = None,
) -> tuple[bool, list[CheckResult]]:
    """Run every check. Returns (overall_success, per-check results).

    overall_success is the AND of all checks — the trial's binary outcome.
    An unknown check type fails closed (returns a failing CheckResult rather
    than raising): a typo in a task YAML must not silently pass a trial.

    `sandbox_host_root` is the host-side path to the trial's sandbox. It is
    forwarded into content-based check specs (see _CONTEXT_CHECKS).
    `agent_commands` is the per-command transcript; it is forwarded into
    agent-trace check specs (see _AGENT_CHECKS). Snapshot-only checks
    ignore both.
    """
    expected = _expected_files_from(specs)
    results: list[CheckResult] = []
    for spec in specs:
        ctype = str(spec.get("type", ""))
        fn = _REGISTRY.get(ctype)
        if fn is None:
            results.append(
                CheckResult(
                    check_type=ctype or "<missing>",
                    passed=False,
                    detail=f"unknown check type {ctype!r} — fix the task YAML",
                )
            )
            continue
        if ctype == "no_extra_files":
            spec = {**spec, "_expected_files": tuple(expected)}
        elif ctype in _CONTEXT_CHECKS:
            spec = {**spec, "_sandbox_host_root": sandbox_host_root}
        elif ctype in _AGENT_CHECKS:
            spec = {**spec, "_agent_commands": agent_commands}
        results.append(fn(snap, spec))
    overall = all(r.passed for r in results)
    return overall, results
